<?php
require_once __DIR__ . '/config.php';
require_once __DIR__ . '/arn_features.php';
arn_require_role(['manager']);
$techId=(int)($_GET['id'] ?? $_POST['technician_id'] ?? 0);
$managerEmail=$_SESSION['email'];
$stmt=$pdo->prepare("SELECT id,name,email,phone,specialization,position,created_at FROM users WHERE id=? AND role LIKE 'tech_%' LIMIT 1"); $stmt->execute([$techId]); $tech=$stmt->fetch();
if(!$tech){http_response_code(404);exit('Technician not found.');}
$manager=$pdo->prepare('SELECT id FROM users WHERE email=? LIMIT 1');$manager->execute([$managerEmail]);$managerId=$manager->fetchColumn()?:null;
$error='';$success='';
if($_SERVER['REQUEST_METHOD']==='POST' && ($_POST['action']??'')==='promote'){
  $newPosition=trim($_POST['new_position']??'');$date=$_POST['promotion_date']??date('Y-m-d');$reason=trim($_POST['reason']??'');
  if($newPosition===''){$error='New position is required.';}else{
    try{$pdo->beginTransaction();$ins=$pdo->prepare('INSERT INTO technician_promotions (technician_id,previous_position,new_position,promotion_date,reason,approved_by) VALUES (?,?,?,?,?,?)');$ins->execute([$techId,$tech['position'],$newPosition,$date,$reason,$managerId]);$up=$pdo->prepare('UPDATE users SET position=? WHERE id=?');$up->execute([$newPosition,$techId]);$pdo->commit();$success='Technician position updated and promotion history recorded.';$tech['position']=$newPosition;}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$error='Promotion failed: '.$e->getMessage();}
  }
}
$stmt=$pdo->prepare("SELECT COUNT(*) FROM service_requests WHERE technician_id=? AND LOWER(status)='completed'");$stmt->execute([$techId]);$completed=(int)$stmt->fetchColumn();
$stmt=$pdo->prepare('SELECT COALESCE(AVG(rating),0),COUNT(*) FROM technician_reviews WHERE technician_id=?');$stmt->execute([$techId]);[$avg,$reviews]=$stmt->fetch(PDO::FETCH_NUM);
$stmt=$pdo->prepare('SELECT r.*,sr.asset_id,sr.problem_category,sr.created_at AS job_created FROM technician_reviews r LEFT JOIN service_requests sr ON sr.id=r.service_request_id WHERE r.technician_id=? ORDER BY r.created_at DESC');$stmt->execute([$techId]);$reviewRows=$stmt->fetchAll();
$stmt=$pdo->prepare('SELECT * FROM technician_promotions WHERE technician_id=? ORDER BY promotion_date DESC,id DESC');$stmt->execute([$techId]);$promotions=$stmt->fetchAll();
$stmt=$pdo->prepare("SELECT id,client_email,asset_id,asset_type,problem_category,status,current_price,amount,created_at FROM service_requests WHERE technician_id=? ORDER BY id DESC LIMIT 100");$stmt->execute([$techId]);$jobs=$stmt->fetchAll();
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=htmlspecialchars($tech['name'])?> | Technician Performance</title><link href="css/bootstrap.min.css" rel="stylesheet"><link href="css/style.css" rel="stylesheet"></head><body style="background:#F8FAFC"><div class="container py-4"><div class="d-flex justify-content-between align-items-center mb-4"><div><h2 class="fw-bold mb-1"><?=htmlspecialchars($tech['name'])?></h2><div class="text-secondary"><?=htmlspecialchars($tech['email'])?> · <?=htmlspecialchars($tech['position']??'Technician')?></div></div><a href="manager-technicians.php" class="btn btn-outline-secondary rounded-pill">Back</a></div><?php if($success):?><div class="alert alert-success"><?=htmlspecialchars($success)?></div><?php endif;?><?php if($error):?><div class="alert alert-danger"><?=htmlspecialchars($error)?></div><?php endif;?>
<div class="row g-3 mb-4"><div class="col-md-3"><div class="bg-white border rounded-4 p-3"><small>Average Rating</small><h3 class="fw-bold mb-0">★ <?=number_format((float)$avg,1)?>/5</h3></div></div><div class="col-md-3"><div class="bg-white border rounded-4 p-3"><small>Total Reviews</small><h3 class="fw-bold mb-0"><?=$reviews?></h3></div></div><div class="col-md-3"><div class="bg-white border rounded-4 p-3"><small>Completed Jobs</small><h3 class="fw-bold mb-0"><?=$completed?></h3></div></div><div class="col-md-3"><div class="bg-white border rounded-4 p-3"><small>Specialization</small><h3 class="fw-bold mb-0"><?=htmlspecialchars($tech['specialization']??'—')?></h3></div></div></div>
<div class="row g-4"><div class="col-lg-7"><div class="bg-white border rounded-4 p-4 mb-4"><h5 class="fw-bold">Customer Reviews</h5><?php foreach($reviewRows as $r):?><div class="border-bottom py-3"><div class="d-flex justify-content-between"><strong><?=htmlspecialchars($r['customer_email'])?></strong><span class="text-warning fw-bold"><?=str_repeat('★',(int)$r['rating']).str_repeat('☆',5-(int)$r['rating'])?></span></div><div class="small text-secondary mb-1">Asset <?=htmlspecialchars($r['asset_id']??'—')?> · Job #<?= (int)$r['service_request_id']?></div><div><?=nl2br(htmlspecialchars($r['review']??''))?></div><small class="text-secondary"><?=htmlspecialchars($r['created_at'])?></small></div><?php endforeach;?><?php if(!$reviewRows):?><p class="text-secondary">No reviews yet.</p><?php endif;?></div>
<div class="bg-white border rounded-4 p-4"><h5 class="fw-bold">Completed / Assigned Jobs</h5><div class="table-responsive"><table class="table"><thead><tr><th>Job</th><th>Asset ID</th><th>Service</th><th>Status</th><th>Price</th></tr></thead><tbody><?php foreach($jobs as $j):?><tr><td>#<?= (int)$j['id']?></td><td class="font-monospace fw-bold"><?=htmlspecialchars($j['asset_id'])?></td><td><?=htmlspecialchars($j['problem_category'])?></td><td><?=htmlspecialchars($j['status'])?></td><td>৳<?=number_format((float)($j['current_price']??$j['amount']??0),2)?></td></tr><?php endforeach;?></tbody></table></div></div></div>
<div class="col-lg-5"><div class="bg-white border rounded-4 p-4 mb-4"><h5 class="fw-bold">Promote / Update Position</h5><form method="post"><input type="hidden" name="action" value="promote"><input type="hidden" name="technician_id" value="<?=$techId?>"><div class="mb-3"><label class="form-label">Previous Position</label><input class="form-control" value="<?=htmlspecialchars($tech['position']??'Technician')?>" disabled></div><div class="mb-3"><label class="form-label">New Position</label><input name="new_position" class="form-control" placeholder="Senior Technician" required></div><div class="mb-3"><label class="form-label">Promotion Date</label><input type="date" name="promotion_date" class="form-control" value="<?=date('Y-m-d')?>" required></div><div class="mb-3"><label class="form-label">Reason / Notes</label><textarea name="reason" class="form-control" rows="4"></textarea></div><button class="btn btn-primary rounded-pill w-100 fw-bold">Record Promotion</button></form></div><div class="bg-white border rounded-4 p-4"><h5 class="fw-bold">Promotion History</h5><?php foreach($promotions as $p):?><div class="border-bottom py-2"><strong><?=htmlspecialchars($p['previous_position']??'—')?> → <?=htmlspecialchars($p['new_position'])?></strong><div class="small text-secondary"><?=htmlspecialchars($p['promotion_date'])?> · <?=htmlspecialchars($p['reason']??'')?></div></div><?php endforeach;?><?php if(!$promotions):?><p class="text-secondary">No promotion history.</p><?php endif;?></div></div></div></div></body></html>
