<?php
require_once __DIR__ . '/config.php';
require_once __DIR__ . '/arn_features.php';
arn_require_role(['manager']);
$email=$_SESSION['email'];
$manager=$pdo->prepare('SELECT id FROM users WHERE email=? LIMIT 1');$manager->execute([$email]);$managerId=$manager->fetchColumn()?:null;
$message='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST' && ($_POST['action']??'')==='update_price'){
  $requestId=(int)($_POST['request_id']??0);$new=(float)($_POST['new_price']??0);$reason=trim($_POST['reason']??'');
  if($requestId<1 || $new<0){$error='Please provide a valid service request and price.';}else{
    try{$pdo->beginTransaction();$stmt=$pdo->prepare('SELECT asset_ref_id,current_price,amount FROM service_requests WHERE id=? FOR UPDATE');$stmt->execute([$requestId]);$job=$stmt->fetch();if(!$job)throw new RuntimeException('Service request not found.');$previous=$job['current_price']!==null?(float)$job['current_price']:($job['amount']!==null?(float)$job['amount']:0);$up=$pdo->prepare('UPDATE service_requests SET current_price=?, original_price=COALESCE(original_price,?), amount=? WHERE id=?');$up->execute([$new,$previous,$new,$requestId]);$assetRef=$job['asset_ref_id']?:null;$hist=$pdo->prepare('INSERT INTO service_price_history (service_request_id,asset_id,previous_price,new_price,changed_by,changed_by_email,reason) VALUES (?,?,?,?,?,?,?)');$hist->execute([$requestId,$assetRef,$previous,$new,$managerId,$email,$reason]);$pdo->commit();$message='Service price updated and the previous value was preserved in price history.';}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$error='Price update failed: '.$e->getMessage();}}
}
$q=trim($_GET['q']??'');$sql="SELECT sr.id,sr.client_email,sr.asset_id,sr.asset_type,sr.problem_category,sr.status,sr.original_price,sr.current_price,sr.amount FROM service_requests sr WHERE 1=1";$params=[];if($q!==''){$sql.=' AND (sr.asset_id LIKE ? OR sr.client_email LIKE ? OR CAST(sr.id AS CHAR) LIKE ?)';$like="%$q%";array_push($params,$like,$like,$like);} $sql.=' ORDER BY sr.id DESC LIMIT 200';$stmt=$pdo->prepare($sql);$stmt->execute($params);$rows=$stmt->fetchAll();
$histories=[];foreach($rows as $r){$h=$pdo->prepare('SELECT previous_price,new_price,changed_by_email,reason,created_at FROM service_price_history WHERE service_request_id=? ORDER BY id DESC');$h->execute([$r['id']]);$histories[$r['id']]=$h->fetchAll();}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Service Price History | ARN QuickFix</title><link href="css/bootstrap.min.css" rel="stylesheet"></head><body style="background:#F8FAFC"><div class="container-fluid px-4 py-4"><div class="d-flex justify-content-between align-items-center mb-4"><div><h2 class="fw-bold mb-1">Service Price History</h2><p class="text-secondary mb-0">Update current prices without destroying previous values.</p></div><a href="manager-dashboard.php" class="btn btn-outline-secondary rounded-pill">Back to Manager Hub</a></div><?php if($message):?><div class="alert alert-success"><?=htmlspecialchars($message)?></div><?php endif;?><?php if($error):?><div class="alert alert-danger"><?=htmlspecialchars($error)?></div><?php endif;?><form class="mb-3"><div class="input-group"><input name="q" class="form-control" value="<?=htmlspecialchars($q)?>" placeholder="Search Asset ID, customer email or request ID"><button class="btn btn-dark">Search</button></div></form><div class="bg-white border rounded-4 p-3"><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Request</th><th>Asset ID</th><th>Customer</th><th>Current Price</th><th>Original Price</th><th>History</th><th>Update</th></tr></thead><tbody><?php foreach($rows as $r):$cur=$r['current_price']!==null?(float)$r['current_price']:(float)($r['amount']??0);$orig=$r['original_price']!==null?(float)$r['original_price']:$cur;?><tr><td>#<?= (int)$r['id']?><div class="small text-secondary"><?=htmlspecialchars($r['problem_category'])?></div></td><td class="font-monospace fw-bold"><?=htmlspecialchars($r['asset_id'])?></td><td><?=htmlspecialchars($r['client_email'])?></td><td>৳<?=number_format($cur,2)?></td><td>৳<?=number_format($orig,2)?></td><td><details><summary><?=count($histories[$r['id']]??[])?> change(s)</summary><?php foreach(($histories[$r['id']]??[]) as $h):?><div class="small border-bottom py-1">৳<?=number_format((float)($h['previous_price']??0),2)?> → ৳<?=number_format((float)$h['new_price'],2)?> · <?=htmlspecialchars($h['changed_by_email']??'')?> · <?=htmlspecialchars($h['created_at'])?><?php if($h['reason']):?><br><?=htmlspecialchars($h['reason'])?><?php endif;?></div><?php endforeach;?></details></td><td><form method="post" class="d-flex gap-1"><input type="hidden" name="action" value="update_price"><input type="hidden" name="request_id" value="<?= (int)$r['id']?>"><input type="number" step="0.01" min="0" name="new_price" class="form-control form-control-sm" placeholder="New price" required><input name="reason" class="form-control form-control-sm" placeholder="Reason"><button class="btn btn-sm btn-primary">Save</button></form></td></tr><?php endforeach;?></tbody></table></div></div></div></body></html>
